apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xy0q7gv2l-dotnet-basic
  janus-idp.io/tekton: xy0q7gv2l-dotnet-basic
  backstage.io/kubernetes-id: xy0q7gv2l-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xy0q7gv2l-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
